global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'loan_model_api'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8000']
        labels:
          service: 'loan_model_api'

  - job_name: 'loan_model_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8001']
        labels:
          service: 'loan_model_exporter'